FROM eclipse-temurin:17
RUN mkdir -p /opt/todoui
WORKDIR /opt/todoui
COPY opentelemetry-javaagent.jar /opt/todoui
#ADD https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar .
COPY todoui/target/todoui-0.0.1-SNAPSHOT.jar /opt/todoui
CMD ["java", "-javaagent:/opt/todoui/opentelemetry-javaagent.jar", "-jar", "todoui-0.0.1-SNAPSHOT.jar"]