apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoui
  template:
    metadata:
      name: todoui
      labels:
        app: todoui
    spec:
      containers:
      - name: todoui
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: POSTGRES_HOST
          value: postgresdb
        - name: OTEL_EXPORTER_JAEGER_ENDPOINT
          value: http://oteldemo-otelcol.otel.svc.cluster.local:14250
        - name: OTEL_SERVICE_NAME
          value: todoui
        - name: OTEL_TRACES_EXPORTER
          value: jaeger
        image: maeddes/todoui:orig
      restartPolicy: Always
