FROM gcr.io/distroless/java17-debian11
COPY target/todoui-0.0.1-SNAPSHOT.jar /opt/todoui/todoui-0.0.1-SNAPSHOT.jar
WORKDIR /opt/todoui
ADD https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar .
ENV JAVA_TOOL_OPTIONS "-javaagent:./opentelemetry-javaagent.jar -Dotel.resource.attributes=service.name=todoui"
CMD ["todoui-0.0.1-SNAPSHOT.jar"]